### ISSUE TITLE
Add support for Compose Multiplatform

### ISSUE THREAD

**Issue by Wavesonics** [pChochura/richtext-compose#2]
Would be a very useful widget!

**Comment by pChochura** [comment]
Unfortunately I'm not familiar with Compose Multiplatform. And this project is no longer actively maintained.
But feel free to create a fork! Good luck

**Comment by troyhen** [comment]
I've been able to convert this to Compose Multiplatform. If anyone is still interested I can post my fork.

**Comment by Wavesonics** [comment]
@troyhen ha, I did the same thing :P

https://github.com/Wavesonics/richtext-compose-multiplatform

Maybe we should poll our efforts
