### ISSUE TITLE
How to Add Custom Text in Editor?

### ISSUE THREAD

**Issue by ErJeetChaudhary** [pChochura/richtext-compose#5]
Hi, I wanted to create extended version of `StyleMapper` like `TokenStyleMapper`. I want to add a text like `**{{edit.token}}**` on button click. Can you please tell me how can I achieve this by extending this library.

**Comment by pChochura** [comment]
Hi! I'm afraid that's not possible using the `StyleMapper`. It allows only to style the text, not alter it. So if you want to be able to do so you'd have to do something like that:

1. Make this method public:

```kotlin
abstract class RichTextValue {
    // [...]
    abstract fun updatedValueAndStyles(value: TextFieldValue): Boolean
    // [...]
}
```

2. Update the text itself right from the ui layer:

```kotlin
var richTextValue by remember {
    mutableStateOf(RichTextValue.get())
}

RichTextEditor(
    value = richTextValue,
    onValueChange = { value = it },
)

Button(
    onClick = {
        val value = richTextValue.value
        richTextValue = value.updatedValueAndStyles(
            value.copy(
                text = "${
                    value.text.take(value.selection.min) // Text before the selection
                }**{{${
                    value.text.substring(
                        value.selection.min,
                        value.selection.max,
                    ) // Text you selected
                }}}**${
                    value.text.substring(value.selection.max) // Text after the selection
                }"
            )
        )
    },
)
```

I think that's what you're after. But I didn't test the code, so it might not work right away. I hope it does and it solves your problem!
Cheers

**Comment by ErJeetChaudhary** [comment]
Thanks, I will try this. Tell me one more thing, how can I convert this `RichTextValue` to html text?
